name: 'Nand2Tetris Grader'
description: 'Grade Nand2Tetris course projects'

inputs:
  dir:
    description: 'Project dir'
    required: true
runs:
  using: actions/checkout@v4
  script:
    - echo Hello, world!
    - ls -la $GITHUB_WORKSPACE
#  using: 'docker'
#  image: docker://pro100kot/nand2tetris-grader:latest
#  args:
#    - ${{ inputs.dir}}

